# Generated by Django 4.0.4 on 2022-06-01 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomType', models.CharField(max_length=80)),
                ('priceRate', models.IntegerField()),
                ('roomDescription', models.CharField(max_length=200)),
                ('room_available', models.BooleanField(default=True)),
                ('roomPictures', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('cleaning', models.BooleanField()),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookroom.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='BookerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('valid_Id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookroom.rooms')),
            ],
        ),
    ]
