# Generated by Django 4.0.4 on 2022-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0002_rooms_end_date_rooms_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(),
        ),
    ]
