# Generated by Django 4.0.4 on 2022-06-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0004_alter_rooms_end_date_alter_rooms_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
