# Generated by Django 4.0.4 on 2022-07-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0005_alter_rooms_end_date_alter_rooms_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookerdetails',
            name='date_of_birth',
        ),
    ]
